import type { TechnicalIterationPlan, VisualQAReport } from "../types/creative-qa";

export interface NaturalBeautyIterationEvidence {
  projectFingerprint: string;
  gradeObject: { id: string; name: string };
  gradeComponent: { id: string; name: string; enabled: boolean };
  retouchComponent: { id: string; name: string };
  visualQA: VisualQAReport;
}

export function createNaturalBeautyIterationPlan(evidence: NaturalBeautyIterationEvidence): TechnicalIterationPlan {
  const criticalColour = evidence.visualQA.findings.filter((finding) => finding.severity === "CRITICAL" && ["COLOUR", "SPECIFICATION", "POLISH", "CATEGORY"].includes(finding.type));
  const sourceEvidence = ["Lens Studio MCP Iteration 0 property readback", `OpenAI Vision ${evidence.visualQA.model ?? "configured model"} Iteration 0 assessment`];
  return {
    id: "technical-plan-natural-beauty-iteration-1", buildId: "learning-build-001-natural-beauty", sourceVisualScore: evidence.visualQA.overallScore, createdAt: "2026-08-14T14:00:00.000Z", projectFingerprint: evidence.projectFingerprint,
    baseline: [{ target: { name: evidence.gradeComponent.name, id: evidence.gradeComponent.id, type: "PostEffectVisual", path: "Camera Object/Effects/Natural Beauty Grade" }, propertyPath: "enabled", value: evidence.gradeComponent.enabled, evidenceSource: "Lens Studio MCP VirtualScene read after Iteration 0" }],
    changes: [
      { id: "disable-faulty-natural-beauty-grade", category: "Colour", visualProblem: criticalColour.map((finding) => finding.description).join(" ") || "The preview has an extreme green and magenta cast.", visualRecommendation: "Restore a neutral camera image before any further beauty tuning.", targetObject: { name: evidence.gradeObject.name, id: evidence.gradeObject.id, type: "SceneObject", path: "Camera Object/Effects/Natural Beauty Grade" }, targetComponentOrAsset: { name: evidence.gradeComponent.name, id: evidence.gradeComponent.id, type: "PostEffectVisual", path: "Camera Object/Effects/Natural Beauty Grade" }, targetPropertyOrParameter: "enabled", currentValue: evidence.gradeComponent.enabled, proposedValueOrOperation: "Set enabled to false with the supported scene setEnabled operation.", reason: "The false colour covers the full frame and is produced by the isolated colour-grade path. Disabling that component removes only the faulty LUT treatment and preserves RetouchVisual for a clean comparison.", expectedVisualResult: "Remove the green and magenta false colour. Preserve the conservative retouch treatment for Iteration 1 assessment.", confidence: "HIGH", reversible: true, evidenceSources: sourceEvidence, status: "READY" },
      { id: "defer-skin-adjustment", category: "Skin", visualProblem: "Skin texture cannot be judged through the false colour.", visualRecommendation: "Reassess skin texture after colour is neutral.", targetObject: null, targetComponentOrAsset: { name: evidence.retouchComponent.name, id: evidence.retouchComponent.id, type: "RetouchVisual", path: "Camera Object/Effects/Natural Beauty Retouch" }, targetPropertyOrParameter: null, currentValue: null, proposedValueOrOperation: null, reason: "The Vision report states that false colour prevents reliable smoothing assessment. Changing retouch now would mix two visual problems.", expectedVisualResult: "Keep retouch values isolated and unchanged until they can be evaluated.", confidence: "HIGH", reversible: false, evidenceSources: sourceEvidence, status: "UNKNOWN" },
      { id: "defer-eye-adjustment", category: "Eyes", visualProblem: "The eye area appears green in the false-colour preview.", visualRecommendation: "Reassess the eye treatment after colour is neutral.", targetObject: null, targetComponentOrAsset: { name: evidence.retouchComponent.name, id: evidence.retouchComponent.id, type: "RetouchVisual", path: "Camera Object/Effects/Natural Beauty Retouch" }, targetPropertyOrParameter: null, currentValue: null, proposedValueOrOperation: null, reason: "The current preview cannot separate LUT colour failure from RetouchVisual eye controls.", expectedVisualResult: "Avoid an unsupported change to the eye controls.", confidence: "HIGH", reversible: false, evidenceSources: sourceEvidence, status: "UNKNOWN" },
      { id: "defer-teeth-assessment", category: "Teeth", visualProblem: "Teeth treatment is not visible enough to assess.", visualRecommendation: "Use a neutral preview with a visible smile before changing teeth whitening.", targetObject: null, targetComponentOrAsset: { name: evidence.retouchComponent.name, id: evidence.retouchComponent.id, type: "RetouchVisual", path: "Camera Object/Effects/Natural Beauty Retouch" }, targetPropertyOrParameter: "teethWhiteningIntensity", currentValue: 0.1, proposedValueOrOperation: null, reason: "The closed-mouth preview does not provide evidence for a value change.", expectedVisualResult: "Preserve the current conservative value until suitable evidence exists.", confidence: "HIGH", reversible: false, evidenceSources: sourceEvidence, status: "NEEDS_HUMAN_INPUT" },
      { id: "unknown-lut-packing", category: "Colour asset", visualProblem: "The generated LUT produced a false-colour channel artefact.", visualRecommendation: "Replace it only after the LUT packing convention is verified.", targetObject: { name: evidence.gradeObject.name, id: evidence.gradeObject.id, type: "SceneObject", path: "Camera Object/Effects/Natural Beauty Grade" }, targetComponentOrAsset: { name: "Natural Beauty LUT", id: "8da2358c-e0d0-4b1c-a475-07948c97f36d", type: "FileTexture", path: "Natural Beauty LUT.png" }, targetPropertyOrParameter: "pixel encoding", currentValue: "SHA-256 7e52f98f5321066e1833318b66a7d3a94e1540524587b4ee683c6255ccfcac57", proposedValueOrOperation: null, reason: "The observed 256 by 16 dimensions do not prove channel order, row direction, or slice packing. A replacement encoding would be a guess.", expectedVisualResult: "No asset replacement is attempted without verified encoding evidence.", confidence: "HIGH", reversible: false, evidenceSources: [...sourceEvidence, "Local read-only inspection of color_correction.graphShader LUT 3D node"], status: "UNKNOWN" },
    ],
    preserve: ["RetouchVisual.faceIndex = 0", "RetouchVisual.softSkinIntensity = 0.25", "RetouchVisual.teethWhiteningIntensity = 0.1", "RetouchVisual.sharpenEyeIntensity = 0.2", "RetouchVisual.eyeWhiteningIntensity = 0.08", "Natural Beauty scene hierarchy", "Original Iteration 0 preview and build evidence"],
    readyOperationCount: 1, requiresHumanConfirmation: true, executionEnabled: false, inspectionMessage: "One isolated supported operation is READY. Disable the faulty colour-grade component. Do not change retouch controls or rewrite the LUT without new evidence.",
  };
}
