"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { productConfig } from "../config/product";
import { categories, type Category, type EarningRecord, type Idea, type PerformanceRecord, type Platform } from "../types/domain";
import { BrowserRepository } from "../services/persistence";
import { LensStudioBuildPanel, LensStudioConnectionPanel, LensStudioStatusBadge } from "./lens-studio-panels";
import { QualityReviewPanels } from "./quality-review-panels";
import { LearningLab } from "./learning-lab";
import type { ServiceHealth, WorkspaceStatus } from "../types/system-health";

export type Section = "overview" | "discover" | "ideas" | "studio" | "learning" | "library" | "analytics" | "earnings" | "settings";

const nav: { section: Section; label: string; icon: string }[] = [
  { section: "overview", label: "Overview", icon: "⌂" }, { section: "discover", label: "Discover", icon: "✦" },
  { section: "ideas", label: "Ideas", icon: "◇" }, { section: "studio", label: "Studio", icon: "▰" },
  { section: "learning", label: "Learning Lab", icon: "◫" }, { section: "library", label: "Library", icon: "▦" },
  { section: "analytics", label: "Analytics", icon: "↗" }, { section: "earnings", label: "Earnings", icon: "◎" },
  { section: "settings", label: "Settings", icon: "⚙" },
];

const realJobs = [
  { id: "soft-flash-test", href: "/studio/soft-flash-test", title: "Soft Flash Test", platform: "Snapchat" as Platform, status: "NEEDS_REVIEW", kind: "TEST_BUILD", progress: 86, steps: 6, total: 7 },
  { id: "learning-build-001-natural-beauty", href: "/learning#build-001", title: "Natural Beauty", platform: "Snapchat" as Platform, status: "AWAITING_HUMAN_REVIEW", kind: "LEARNING_BUILD", progress: 92, steps: 11, total: 12 },
];

export function EffectLabApp({ section = "overview" }: { section?: Section }) {
  const [ideas, setIdeas] = useState<Idea[]>([]);
  const [performance, setPerformance] = useState<PerformanceRecord[]>([]);
  const [earnings, setEarnings] = useState<EarningRecord[]>([]);
  const [workspace, setWorkspace] = useState<WorkspaceStatus | null>(null);
  const [toast, setToast] = useState<string | null>(null);
  const [theme, setTheme] = useState<"dark" | "light">("dark");
  const [mobileNav, setMobileNav] = useState(false);
  const [hydrated, setHydrated] = useState(false);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(null), 2600); };

  useEffect(() => {
    const savedTheme = window.localStorage.getItem("effect-lab-theme");
    if (savedTheme === "light") window.queueMicrotask(() => setTheme("light"));
    fetch("/api/workspace-status", { cache: "no-store" }).then(async (response) => {
      if (!response.ok) throw new Error("System status is not available.");
      const status = await response.json() as WorkspaceStatus;
      setWorkspace(status);
      const repository = new BrowserRepository(window.localStorage, status.demoIdeas, "effect-lab-ideas-v1", status.demoDataEnabled);
      const [storedIdeas, storedPerformance, storedEarnings] = await Promise.all([repository.listIdeas(), repository.listPerformance(), repository.listEarnings()]);
      setIdeas(storedIdeas); setPerformance(storedPerformance); setEarnings(storedEarnings);
    }).catch(() => {
      const repository = new BrowserRepository(window.localStorage);
      void Promise.all([repository.listIdeas(), repository.listPerformance(), repository.listEarnings()]).then(([storedIdeas, storedPerformance, storedEarnings]) => { setIdeas(storedIdeas); setPerformance(storedPerformance); setEarnings(storedEarnings); });
    }).finally(() => setHydrated(true));
  }, []);

  useEffect(() => {
    if (!hydrated) return;
    const repository = new BrowserRepository(window.localStorage, workspace?.demoIdeas ?? [], "effect-lab-ideas-v1", workspace?.demoDataEnabled ?? false);
    void Promise.all(ideas.map((idea) => repository.saveIdea(idea)));
  }, [hydrated, ideas, workspace]);

  const changeTheme = (value: "dark" | "light") => { setTheme(value); window.localStorage.setItem("effect-lab-theme", value); };
  return <div className={`app-shell ${theme}`}>
    <aside className={`sidebar ${mobileNav ? "open" : ""}`}><Link href="/" className="brand" aria-label={`${productConfig.name} home`}><span className="brand-mark"><i /></span><span>{productConfig.name}</span></Link><nav aria-label="Main navigation">{nav.map((item) => <Link key={item.section} href={item.section === "overview" ? "/" : `/${item.section}`} className={section === item.section ? "active" : ""}><span className="nav-icon">{item.icon}</span>{item.label}</Link>)}</nav><div className="sidebar-foot"><div className="connection-dot"><span /><div><strong>Local workspace</strong><small>{workspace?.mode === "development" && workspace.demoDataEnabled ? "Demo data is on" : "Real records only"}</small></div></div><div className="profile"><span>EL</span><div><strong>{productConfig.name}</strong><small>Local workspace</small></div></div></div></aside>
    <main className="main"><header className="topbar"><button className="menu-button" onClick={() => setMobileNav(!mobileNav)} aria-label="Open navigation">☰</button><div className="search"><span>⌕</span><input aria-label="Search is unavailable" placeholder="Search is not available" disabled /></div><div className="top-actions"><button className="icon-button" onClick={() => changeTheme(theme === "dark" ? "light" : "dark")} aria-label="Change theme">◐</button><Link className="primary-button compact" href="/ideas">＋ New idea</Link></div></header><div className="content">
      {section === "overview" && <Overview ideas={ideas} performance={performance} earnings={earnings} workspace={workspace} />}
      {section === "discover" && <Discover />}
      {section === "ideas" && <Ideas ideas={ideas} setIdeas={setIdeas} notify={notify} />}
      {section === "studio" && <Studio />}
      {section === "learning" && <LearningLab workspace={workspace} />}
      {section === "library" && <Library ideas={ideas} />}
      {section === "analytics" && <Analytics performance={performance} />}
      {section === "earnings" && <Earnings earnings={earnings} setEarnings={setEarnings} notify={notify} />}
      {section === "settings" && <Settings theme={theme} setTheme={changeTheme} workspace={workspace} />}
    </div></main>{toast && <div className="toast"><span>✓</span>{toast}</div>}
  </div>;
}

function Overview({ ideas, performance, earnings, workspace }: { ideas: Idea[]; performance: PerformanceRecord[]; earnings: EarningRecord[]; workspace: WorkspaceStatus | null }) {
  const today = new Date().toISOString().slice(0, 10);
  const paid = earnings.filter((item) => item.status === "Paid").reduce((total, item) => total + item.amount, 0);
  const snapUses = sumMetric(performance.filter((item) => item.platform === "Snapchat"), "uses");
  const tikTokUses = sumMetric(performance.filter((item) => item.platform === "TikTok"), "uses");
  const stats = [["Ideas today", ideas.filter((item) => item.createdDate === today).length, "violet"], ["Approved ideas", ideas.filter((item) => item.status === "APPROVED").length, "mint"], ["Ready to build", ideas.filter((item) => item.status === "APPROVED").length, "amber"], ["Building", 0, "blue"], ["Needs review", 1, "rose"], ["Published", 0, "slate"]] as const;
  const activities = [...ideas.slice(-3).map((item) => ({ text: `${item.title} was saved.`, date: item.createdDate })), ...earnings.slice(-2).map((item) => ({ text: `A ${item.platform} payout was recorded for ${item.effect}.`, date: item.date }))].sort((a, b) => b.date.localeCompare(a.date));
  const nextBuilds = ideas.filter((item) => item.status === "APPROVED" || item.status === "SAVED").slice(0, 3);
  return <><PageHeading eyebrow="LOCAL WORKSPACE" title="Effect Lab" text="Review the real state of your local effect workspace." />
    <section className="metric-grid" aria-label="Workflow summary">{stats.map(([label, value, tone]) => <article className="metric-card" key={label}><div className={`metric-symbol ${tone}`}>{label === "Published" ? "✓" : "◌"}</div><span>{label}</span><div className="metric-value">{value}</div><small>Local records</small></article>)}</section>
    <section className="overview-grid"><div className="panel performance-panel"><PanelHead title="Performance" subtitle={performance.length ? "Manual or connected records" : "No data yet"} action="View analytics" href="/analytics" /><div className="platform-summary"><div><PlatformBadge platform="Snapchat" /><strong>{snapUses ?? "—"}</strong><small>{snapUses === null ? "No data yet" : "uses"}</small></div><div><PlatformBadge platform="TikTok" /><strong>{tikTokUses ?? "—"}</strong><small>{tikTokUses === null ? "No data yet" : "uses"}</small></div></div></div><div className="panel activity-panel"><PanelHead title="Activity" subtitle="Recorded local events" />{activities.length ? <div className="activity-list">{activities.map((item) => <div className="activity" key={`${item.text}-${item.date}`}><span className="mint">✓</span><div><strong>{item.text}</strong><small>{item.date}</small></div></div>)}</div> : <EmptyState title="No activity yet" text="Recorded actions will appear here." />}</div></section>
    <section className="section-block"><div className="section-title"><div><span className="eyebrow">NEXT BUILDS</span><h2>Recommended next builds</h2><p>Approved and saved ideas appear here.</p></div></div>{nextBuilds.length ? <div className="recommend-grid">{nextBuilds.map((idea, index) => <RecommendationCard key={idea.id} idea={idea} index={index} />)}</div> : <EmptyState title="No builds are ready" text="Create an idea. Approve it when it is ready." />}</section>
    <section className="lower-grid"><div className="panel workflow-panel"><PanelHead title="Production flow" subtitle="One genuine test build" action="Open Studio" href="/studio" /><div className="workflow-bars"><div><span>Needs review</span><div><i className="rose" style={{ width: "86%" }} /></div><strong>1</strong></div></div></div><div className="panel earnings-mini"><PanelHead title="Confirmed earnings" subtitle={earnings.length ? "Manual records" : "No data yet"} action="Open earnings" href="/earnings" /><strong>{paid ? formatMoney(paid, earnings.find((item) => item.status === "Paid")?.currency ?? "GBP") : "0"}</strong><small>No estimate is added.</small></div></section>
    {workspace?.mode === "development" && workspace.demoDataEnabled && <div className="notice"><span>!</span><div><strong>Demo data is on</strong><p>Development examples are visible.</p></div></div>}
  </>;
}

function Discover() { return <><PageHeading eyebrow="OPPORTUNITY DISCOVERY" title="Discover" text="Use a connected research source to find current opportunities." /><div className="notice"><span>i</span><div><strong>Trend data is not connected</strong><p>No live research provider is configured.</p></div></div><EmptyState title="No opportunities yet" text="Connect a research provider in a future update." /></>; }

function Ideas({ ideas, setIdeas, notify }: { ideas: Idea[]; setIdeas: React.Dispatch<React.SetStateAction<Idea[]>>; notify: (message: string) => void }) {
  const [showForm, setShowForm] = useState(false); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [platform, setPlatform] = useState<Platform>("Snapchat"); const [category, setCategory] = useState<Category>("Beauty");
  const save = () => { const cleanTitle = title.trim(); const cleanDescription = description.trim(); if (!cleanTitle || !cleanDescription) return; const idea: Idea = { id: `idea-${crypto.randomUUID()}`, title: cleanTitle, hook: cleanDescription, description: cleanDescription, platforms: [platform], categories: [category], interactionType: "Not defined", targetUserBehaviour: "Not defined", technicalApproach: "Not defined", requiredAssets: [], publicFacingText: [], noveltyExplanation: "Not assessed", risks: [], buildComplexity: "Moderate", estimatedEffort: "Not estimated", status: "DRAFT", createdDate: new Date().toISOString().slice(0, 10), scores: { trend: 0, originality: 0, shareability: 0, replay: 0, potential: 0 }, saturation: "Low", recommendationReason: "Not assessed", demo: false }; setIdeas((all) => [...all, idea]); setTitle(""); setDescription(""); setShowForm(false); notify("The idea was saved."); };
  const update = (id: string, status: Idea["status"]) => { setIdeas((all) => all.map((item) => item.id === id ? { ...item, status } : item)); notify(`The idea is now ${status.toLowerCase()}.`); };
  return <><PageHeading eyebrow="IDEAS" title="Ideas" text="Create ideas by hand. AI generation is unavailable until a real provider is connected." actions={<button className="primary-button" onClick={() => setShowForm(!showForm)}>{showForm ? "Cancel" : "＋ Create idea"}</button>} />{showForm && <section className="idea-composer panel"><div className="composer-top"><div><h2>Create an idea</h2><p>Add a real concept to this local workspace.</p></div></div><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Idea name" aria-label="Idea name" /><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Describe the effect." aria-label="Idea description" /><div className="comparison-selects"><select value={platform} onChange={(event) => setPlatform(event.target.value as Platform)} aria-label="Platform"><option>Snapchat</option><option>TikTok</option></select><select value={category} onChange={(event) => setCategory(event.target.value as Category)} aria-label="Category">{categories.map((item) => <option key={item}>{item}</option>)}</select><button className="primary-button" disabled={!title.trim() || !description.trim()} onClick={save}>Save idea</button></div></section>}{ideas.length ? <div className="idea-list">{ideas.map((idea) => <article key={idea.id}><div className="idea-number">{idea.scores.potential || "—"}</div><div className="idea-main"><div className="card-meta"><PlatformBadge platform={idea.platforms[0]} />{idea.categories.slice(0, 2).map((item) => <span className="tag" key={item}>{item}</span>)}</div><h3>{idea.title}</h3><p>{idea.hook}</p></div><div className="idea-status"><span className={idea.status.toLowerCase()}>{idea.status}</span><small>{idea.scores.potential ? "Potential score" : "Not scored"}</small></div><div className="card-actions"><button onClick={() => update(idea.id, "REJECTED")}>Reject</button><button onClick={() => update(idea.id, "SAVED")}>Save</button><button onClick={() => update(idea.id, "APPROVED")}>Approve</button></div></article>)}</div> : <EmptyState title="No ideas yet" text="Create an idea to start." />}</>;
}

function Studio() { return <><PageHeading eyebrow="PRODUCTION" title="Studio" text="Track real builds from preparation to human review." actions={<LensStudioStatusBadge />} /><div className="studio-top"><div className="panel connection-panel"><div><span className="lens-mark">LS</span><div><h3>Lens Studio</h3><p>Use Settings to inspect the active MCP target.</p></div></div><Link className="wide-link" href="/settings">Open settings</Link></div><div className="manual-panel"><span>!</span><div><h3>TikTok workflow</h3><p>Manual Effect House step required.</p></div><button disabled title="A real build pack is required first.">No build pack</button></div></div><div className="kanban-head"><div><h2>Production board</h2><p>Two genuine build records</p></div></div><div className="kanban"><section><header><span>Needs review</span><b>{realJobs.length}</b></header>{realJobs.map((job) => <Link className="job-card" href={job.href} key={job.id} data-build-id={job.id}><div className="card-meta"><PlatformBadge platform={job.platform} /><span>{job.kind}</span></div><h3>{job.title}</h3><p>{job.id === "soft-flash-test" ? "Historical Soft Flash evidence is stored with this build." : "Automated checks are complete. A person must review this learning build."}</p><div className="progress"><i style={{ width: `${job.progress}%` }} /></div><small>{job.steps}/{job.total} stages complete <b>Open job →</b></small></Link>)}</section></div></>; }

function Library({ ideas }: { ideas: Idea[] }) { const [query, setQuery] = useState(""); const [filter, setFilter] = useState("All"); const results = useMemo(() => ideas.filter((idea) => (filter === "All" || idea.platforms.includes(filter as Platform)) && `${idea.title} ${idea.categories}`.toLowerCase().includes(query.toLowerCase())), [ideas, query, filter]); return <><PageHeading eyebrow="LOCAL LIBRARY" title="Library" text="Search real ideas stored in this browser." /><div className="library-tools"><div className="search large"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search the library" aria-label="Search library" /></div><select value={filter} onChange={(event) => setFilter(event.target.value)} aria-label="Platform filter"><option>All</option><option>Snapchat</option><option>TikTok</option></select></div>{results.length ? <div className="library-table"><div className="table-row table-head"><span>Effect</span><span>Platform</span><span>Categories</span><span>Status</span><span>Potential</span><span>Created</span></div>{results.map((idea) => <div className="table-row" key={idea.id}><span><div><strong>{idea.title}</strong><small>{idea.hook}</small></div></span><span>{idea.platforms.map((item) => <PlatformBadge key={item} platform={item} />)}</span><span>{idea.categories.slice(0, 2).map((item) => <b className="tag" key={item}>{item}</b>)}</span><span><b className={`status ${idea.status.toLowerCase()}`}>{idea.status}</b></span><span>{idea.scores.potential ? `${idea.scores.potential}/10` : "Not scored"}</span><span>{idea.createdDate}</span></div>)}</div> : <EmptyState title="No library records" text="Saved ideas will appear here." />}</>; }

function Analytics({ performance }: { performance: PerformanceRecord[] }) { const metrics = (["views", "opens", "uses", "shares", "saves", "replays"] as const).map((key) => [key, sumMetric(performance, key)] as const); return <><PageHeading eyebrow="PERFORMANCE" title="Analytics" text="Only stored manual or connected records appear here." />{performance.length ? <><div className="analytics-stats">{metrics.map(([key, value]) => <div className="panel" key={key}><span>{key}</span><strong>{value ?? "—"}</strong><small>{value === null ? "Not available" : "Recorded total"}</small></div>)}</div><div className="panel payout-table"><PanelHead title="Performance records" subtitle="Unknown values remain empty" />{performance.map((record) => <div className="table-row" key={record.id}><span>{record.date}</span><span><PlatformBadge platform={record.platform} /></span><span>Uses: {record.uses ?? "—"}</span><span>Shares: {record.shares ?? "—"}</span></div>)}</div></> : <><div className="notice"><span>i</span><div><strong>No Snapchat performance data yet</strong><p>No TikTok performance data exists either.</p></div></div><EmptyState title="No analytics yet" text="Add real platform data when it is available." /></>}</>; }

function Earnings({ earnings, setEarnings, notify }: { earnings: EarningRecord[]; setEarnings: React.Dispatch<React.SetStateAction<EarningRecord[]>>; notify: (message: string) => void }) { const [showForm, setShowForm] = useState(false); const [effect, setEffect] = useState(""); const [programme, setProgramme] = useState(""); const [amount, setAmount] = useState(""); const [currency, setCurrency] = useState("GBP"); const [platform, setPlatform] = useState<Platform>("Snapchat"); const save = async () => { const numeric = Number(amount); if (!effect.trim() || !programme.trim() || !Number.isFinite(numeric) || numeric < 0) return; const record: EarningRecord = { id: `earning-${crypto.randomUUID()}`, platform, effect: effect.trim(), programme: programme.trim(), amount: numeric, currency: currency.trim().toUpperCase(), date: new Date().toISOString().slice(0, 10), status: "Paid", notes: "" }; await new BrowserRepository(window.localStorage).saveEarning(record); setEarnings((all) => [...all, record]); setShowForm(false); setEffect(""); setProgramme(""); setAmount(""); notify("The payout was recorded."); }; return <><PageHeading eyebrow="PAYOUTS" title="Earnings" text="Keep Snapchat and TikTok payout records separate." actions={<button className="primary-button" onClick={() => setShowForm(!showForm)}>{showForm ? "Cancel" : "＋ Add payout"}</button>} />{showForm && <section className="idea-composer panel"><h2>Add a payout</h2><div className="comparison-selects"><select value={platform} onChange={(event) => setPlatform(event.target.value as Platform)}><option>Snapchat</option><option>TikTok</option></select><input value={effect} onChange={(event) => setEffect(event.target.value)} placeholder="Effect" /><input value={programme} onChange={(event) => setProgramme(event.target.value)} placeholder="Programme" /><input type="number" min="0" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Amount" /><input value={currency} onChange={(event) => setCurrency(event.target.value)} placeholder="Currency" /><button className="primary-button" onClick={() => void save()}>Save payout</button></div></section>}{earnings.length ? <div className="panel payout-table"><PanelHead title="Payout records" subtitle="Manual records" /><div className="table-row table-head"><span>Effect</span><span>Platform</span><span>Programme</span><span>Date</span><span>Status</span><span>Amount</span></div>{earnings.map((record) => <div className="table-row" key={record.id}><span>{record.effect}</span><span><PlatformBadge platform={record.platform} /></span><span>{record.programme}</span><span>{record.date}</span><span><b className={`status ${record.status.toLowerCase()}`}>{record.status}</b></span><span><strong>{formatMoney(record.amount, record.currency)}</strong></span></div>)}</div> : <EmptyState title="No earnings recorded yet" text="Add a confirmed payout by hand." />}</>; }

function Settings({ theme, setTheme, workspace }: { theme: string; setTheme: (value: "dark" | "light") => void; workspace: WorkspaceStatus | null }) { const serverState = workspace?.services.find((item) => item.id === "lens-studio")?.state ?? "DISCONNECTED"; return <><PageHeading eyebrow="WORKSPACE" title="Settings" text="Review real system state and local settings." actions={<span className="status waiting">Mode: {workspace?.mode ?? "Production"}</span>} />{workspace?.mode === "development" && workspace.demoDataEnabled && <div className="notice"><span>!</span><div><strong>Demo data is on</strong><p>Development examples are visible.</p></div></div>}<div className="settings-grid"><section className="panel"><PanelHead title="Appearance" subtitle="Saved on this device" /><div className="setting-row"><div><strong>Interface theme</strong><p>Choose a theme.</p></div><div className="segmented"><button className={theme === "dark" ? "active" : ""} onClick={() => setTheme("dark")}>Dark</button><button className={theme === "light" ? "active" : ""} onClick={() => setTheme("light")}>Light</button></div></div></section><LensStudioConnectionPanel /><section className="panel"><PanelHead title="Current Lens Studio target" subtitle={workspace?.lensProject?.checkedAt ? `Checked ${new Date(workspace.lensProject.checkedAt).toLocaleString()}` : "Not checked"} /><dl className="lens-meta"><dt>MCP server</dt><dd>{serverState}</dd><dt>Project</dt><dd>{workspace?.lensProject?.lensName ?? "Unknown"}</dd><dt>Sandbox</dt><dd>{workspace?.sandbox.status ?? "UNKNOWN"}</dd><dt>Connection source</dt><dd>{workspace?.lensConnectionSource ?? "UNKNOWN"}</dd><dt>Last verified</dt><dd>{workspace?.lensLastVerified ? new Date(workspace.lensLastVerified).toLocaleString() : "Not verified"}</dd>{workspace?.lensProject && <><dt>Project file</dt><dd>{workspace.lensProject.projectFile ?? "Unknown"}</dd><dt>Project folder</dt><dd>{workspace.lensProject.projectFolder ?? "Unknown"}</dd><dt>Fingerprint</dt><dd><code>{workspace.lensProject.projectFingerprint}</code></dd><dt>Key objects</dt><dd>{workspace.lensProject.keySceneObjects.join(", ") || "None"}</dd></>}</dl><div className="notice"><span>{workspace?.sandbox.status === "VERIFIED" ? "✓" : "!"}</span><div><strong>{workspace?.sandbox.status === "VERIFIED" ? "The training project is verified" : "The training project is not open"}</strong><p>{workspace?.sandbox.reasons.join(" ") || "The live endpoint, Lens name, project path, Soft Flash check, and fingerprint passed."}</p></div></div></section><SystemHealth services={workspace?.services ?? []} /><section className="panel"><PanelHead title="TikTok" subtitle="Manual Effect House workflow" /><div className="provider-row"><span className="tiktok-mark">T</span><div><strong>Effect House</strong><p>Manual Effect House step required.</p></div><b className="manual">UNAVAILABLE</b></div></section></div></>; }

function SystemHealth({ services }: { services: ServiceHealth[] }) { const [selected, setSelected] = useState<string | null>(null); return <section className="panel"><PanelHead title="System Health" subtitle="Live and configured services" />{services.length ? services.map((service) => <div key={service.id} className="provider-row"><button className="wide-button" onClick={() => setSelected(selected === service.id ? null : service.id)}><span>{service.label}</span><b className={service.state === "CONNECTED" ? "connected" : "manual"}>{service.state}</b></button>{selected === service.id && <div className="reason"><p><strong>Last successful check:</strong> {service.lastSuccessfulCheck ? new Date(service.lastSuccessfulCheck).toLocaleString() : "None"}</p>{service.error && <p><strong>Error:</strong> {service.error}</p>}<p><strong>Next action:</strong> {service.nextAction}</p></div>}</div>) : <p>System status is not available.</p>}</section>; }

function PageHeading({ eyebrow, title, text, actions }: { eyebrow?: string; title: string; text: string; actions?: React.ReactNode }) { return <div className="page-heading"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1><p>{text}</p></div>{actions && <div className="heading-actions">{actions}</div>}</div>; }
function PanelHead({ title, subtitle, action, href = "#" }: { title: string; subtitle: string; action?: string; href?: string }) { return <div className="panel-head"><div><h3>{title}</h3><p>{subtitle}</p></div>{action && href !== "#" && <Link href={href}>{action} →</Link>}</div>; }
function PlatformBadge({ platform }: { platform: Platform }) { return <span className={`platform-badge ${platform.toLowerCase()}`}>{platform === "Snapchat" ? "S" : "T"} {platform}</span>; }
function RecommendationCard({ idea, index }: { idea: Idea; index: number }) { return <article className="recommend-card"><div className={`concept-art art-${index}`}><div className="art-orbit" /><span>IDEA</span></div><div className="recommend-body"><div className="card-meta"><PlatformBadge platform={idea.platforms[0]} /><span>{idea.buildComplexity}</span></div><h3>{idea.title}</h3><p>{idea.hook}</p><div className="score-row"><span><b>{idea.scores.potential || "—"}</b> Potential</span></div><Link href="/ideas">Review idea <span>→</span></Link></div></article>; }
function EmptyState({ title, text }: { title: string; text: string }) { return <div className="panel learning-empty"><span>◇</span><h2>{title}</h2><p>{text}</p></div>; }
function sumMetric(records: PerformanceRecord[], key: keyof Pick<PerformanceRecord, "views" | "opens" | "uses" | "shares" | "saves" | "replays">) { const values = records.map((item) => item[key]).filter((item): item is number => typeof item === "number"); return values.length ? values.reduce((total, item) => total + item, 0) : null; }
function formatMoney(amount: number, currency: string) { try { return new Intl.NumberFormat(undefined, { style: "currency", currency }).format(amount); } catch { return `${currency} ${amount.toFixed(2)}`; } }

export function StudioJobDetail() { return <EffectLabFrame section="studio"><Link className="back-link" href="/studio">← Back to Studio</Link><PageHeading eyebrow="BUILD RECORD" title="Build not found" text="This production record does not exist." /><EmptyState title="No build record" text="Return to Studio and select a real build." /></EffectLabFrame>; }

export function SoftFlashJobDetail() { return <EffectLabFrame section="studio"><Link className="back-link" href="/studio">← Back to Studio</Link><PageHeading eyebrow="CONTROLLED SNAPCHAT BUILD" title="Soft Flash Test" text="Technical success does not equal visual or experience quality." actions={<LensStudioStatusBadge />} /><div className="soft-flash-intro"><div><span>Purpose</span><p>Test the official Lens Studio MCP workflow with one simple built-in camera treatment.</p></div><div><span>Safety</span><p>No face shape change. No heavy smoothing. No publishing.</p></div><div><span>Final gate</span><p>A person must review the result before submission.</p></div></div><LensStudioBuildPanel /><QualityReviewPanels /></EffectLabFrame>; }

function EffectLabFrame({ children, section }: { children: React.ReactNode; section: Section }) { return <div className="app-shell dark"><aside className="sidebar"><Link href="/" className="brand"><span className="brand-mark"><i /></span><span>{productConfig.name}</span></Link><nav>{nav.map((item) => <Link key={item.section} href={item.section === "overview" ? "/" : `/${item.section}`} className={section === item.section ? "active" : ""}><span className="nav-icon">{item.icon}</span>{item.label}</Link>)}</nav></aside><main className="main"><header className="topbar"><div className="search"><span>⌕</span><input placeholder="Search is not available" disabled /></div></header><div className="content">{children}</div></main></div>; }
