"use client";

import { useMemo, useState } from "react";
import { censusDistribution } from "../services/preset-census";
import { emptySandboxConfirmation, evaluateSandboxInstantiation, TRAINING_SANDBOX_LENS_NAME, TRAINING_SANDBOX_PROJECT_PATH } from "../services/training-sandbox-safety";
import type { CensusSnapshot, PresetCategory, PresetRecord } from "../types/preset-census";

export function PresetLibraryView({ snapshot }: { snapshot: CensusSnapshot }) {
  const [category, setCategory] = useState("All"); const [level, setLevel] = useState("All"); const [confidence, setConfidence] = useState("All"); const [source, setSource] = useState("All"); const [selected, setSelected] = useState<PresetRecord | null>(null);
  const records = snapshot.presets;
  const filtered = useMemo(() => records.filter((record) => (category === "All" || [record.inferredCategory.value, ...record.secondaryCategories.map((item) => item.value)].includes(category as PresetCategory)) && (level === "All" || record.inspectionLevel === level) && (confidence === "All" || record.confidence === confidence) && (source === "All" || record.source === source)), [records, category, level, confidence, source]);
  const distribution = censusDistribution(records);
  const inspected = records.filter((record) => record.inspectionLevel !== "DISCOVERED").length;
  const deep = records.filter((record) => record.inspectionLevel === "DEEPLY_INSPECTED").length;
  return <>
    <section className="learning-metrics census-metrics" aria-label="Preset census summary">{[["Total presets", records.length], ["Inspected", inspected], ["Uninspected", records.length - inspected], ["Deeply inspected", deep], ["High confidence", records.filter((record) => record.confidence === "HIGH").length]].map(([label, value]) => <article className="panel" key={label}><span>{label}</span><strong>{value}</strong><small>Lens Studio evidence</small></article>)}</section>
    <div className="census-summary-grid"><section className="panel census-distribution"><header><span className="eyebrow">CATEGORY DISTRIBUTION</span><h2>Inferred from metadata</h2><p>Counts are classification inferences. They are not verified implementation knowledge.</p></header><div>{distribution.map((item) => <span key={item.category}><b>{item.category}</b><strong>{item.count}</strong></span>)}</div></section><section className="panel confidence-distribution"><span className="eyebrow">CONFIDENCE</span><h2>Metadata completeness</h2>{["HIGH", "MEDIUM", "LOW"].map((item) => <div key={item}><span>{item}</span><i><b style={{ width: `${records.length ? records.filter((record) => record.confidence === item).length / records.length * 100 : 0}%` }} /></i><strong>{records.filter((record) => record.confidence === item).length}</strong></div>)}</section></div>
    <div className="filterbar census-filters"><select value={category} onChange={(event) => setCategory(event.target.value)} aria-label="Preset category"><option>All</option>{distribution.map((item) => <option key={item.category}>{item.category}</option>)}</select><select value={level} onChange={(event) => setLevel(event.target.value)} aria-label="Inspection level"><option>All</option>{["DISCOVERED", "METADATA_INSPECTED", "SCENE_INSPECTED", "DEEPLY_INSPECTED"].map((item) => <option key={item}>{item}</option>)}</select><select value={confidence} onChange={(event) => setConfidence(event.target.value)} aria-label="Confidence"><option>All</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select><select value={source} onChange={(event) => setSource(event.target.value)} aria-label="Source"><option>All</option><option>OFFICIAL_SNAP</option><option>LOCAL_OFFICIAL_RESOURCE</option><option>UNKNOWN</option></select><span>{filtered.length} presets</span></div>
    <div className="preset-library-layout"><section className="panel preset-table"><div className="preset-row preset-head"><span>Exact Lens Studio name</span><span>Inferred category</span><span>Inspection</span><span>Confidence</span></div>{filtered.map((record) => <button className={`preset-row ${selected?.id === record.id ? "selected" : ""}`} key={record.id} onClick={() => setSelected(record)}><span><strong>{record.exactName}</strong><small>{String(record.rawMetadata.description ?? "No description returned")}</small></span><span>{record.inferredCategory.value}<small>{record.inferredCategory.authority}</small></span><span>{record.inspectionLevel.replaceAll("_", " ")}</span><span>{record.confidence}</span></button>)}</section>{selected ? <PresetDetail record={selected} /> : <section className="panel preset-detail empty-detail"><span>◇</span><h2>Select a preset</h2><p>Open its evidence, known fields, unknown fields, Pattern Cards, and inspection history.</p></section>}</div>
  </>;
}

function PresetDetail({ record }: { record: PresetRecord }) {
  const known = Object.entries(record.rawMetadata).filter(([, value]) => value !== null && value !== "");
  const unknown = ["scene objects", "hierarchy", "components", "assets", "materials", "textures", "shaders", "scripts", "properties", "behaviours", "triggers", "dependencies"].filter((field) => !Object.keys(record.rawMetadata).some((key) => key.toLowerCase().includes(field.replace(" ", ""))));
  return <section className="panel preset-detail"><header><span className="eyebrow">PRESET RECORD</span><h2>{record.exactName}</h2><p>{record.source} · {record.inspectionLevel}</p></header><div className="inference-callout"><strong>{record.inferredCategory.value}</strong><span>{record.inferredCategory.authority}</span><p>{record.inferredCategory.rationale}</p></div><h3>Actual metadata returned</h3><pre>{JSON.stringify(record.rawMetadata, null, 2)}</pre><h3>Known information</h3><dl>{known.map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl><h3>Unknown information</h3><p>{unknown.length ? unknown.join(", ") : "No additional fields were inferred."}</p><h3>Pattern Cards</h3><p>{record.patternCardIds.length ? record.patternCardIds.join(", ") : "None"}</p><h3>Inspection history</h3>{record.inspectionHistory.map((event, index) => <div className="inspection-event" key={`${event.occurredAt}-${index}`}><span>{event.level}</span><b>{event.result}</b><p>{event.note}</p><small>{event.capability} · {new Date(event.occurredAt).toLocaleString()}</small></div>)}</section>;
}

export function FirstWaveView({ snapshot, busy, inspectWave }: { snapshot: CensusSnapshot; busy: string | null; inspectWave: () => void }) {
  const selection = snapshot.representativeSelection;
  const [sandbox] = useState(emptySandboxConfirmation());
  const first = selection?.selected[0] ? snapshot.presets.find((record) => record.id === selection.selected[0].presetId) : null;
  const decision = first ? evaluateSandboxInstantiation(first, sandbox, false) : null;
  if (!selection) return <div className="panel learning-empty"><span>◇</span><h2>No proposed inspection set</h2><p>Run the preset census first. Effect Lab will select representatives from current Lens Studio metadata.</p></div>;
  return <><section className="panel wave-summary"><header><div><span className="eyebrow">PROPOSED FIRST WAVE</span><h2>{selection.selected.length} representative presets</h2><p>This set prioritises coverage and avoids metadata-level near duplicates. Review it before any future Lens Studio change.</p></div><div><strong>{selection.beautyRelatedCount}</strong><small>beauty, makeup, or camera related</small></div></header><div className="wave-coverage">{selection.categoryCoverage.map((item) => <span key={item.category}>{item.category} <b>{item.count}</b></span>)}</div><button className="primary-button" disabled={busy !== null || !selection.selected.length} onClick={inspectWave}>{busy === "wave" ? "Inspecting metadata…" : "Run read-only first wave"}</button></section>
    <section className="wave-list">{selection.selected.map((item, index) => { const record = snapshot.presets.find((preset) => preset.id === item.presetId); return <article className="panel" key={item.presetId}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{item.exactName}</h3><p>{item.categories.join(" · ")}</p><small>{item.reasons.join(" ")}</small></div><b className={record?.inspectionLevel === "METADATA_INSPECTED" ? "inspected" : ""}>{record?.inspectionLevel ?? "DISCOVERED"}</b></article>; })}</section>
    <section className="panel sandbox-gate"><div><span>ACTION REQUIRED</span><h2>Open a disposable blank Lens Studio project for Learning Lab inspection.</h2><p>Set the Lens name to <b>{TRAINING_SANDBOX_LENS_NAME}</b>. Keep the saved project at <b>{TRAINING_SANDBOX_PROJECT_PATH}</b>. Effect Lab cannot verify a safe reset or create the project with the current read-only workflow.</p></div><dl><dt>Project confirmed</dt><dd>NO</dd><dt>Preset confirmed</dt><dd>NO</dd><dt>Safe reset verified</dt><dd>NO</dd><dt>Instantiation</dt><dd>BLOCKED</dd></dl>{decision && <small>{decision.reasons.join(" ")}</small>}</section></>;
}
